#!/usr/bin/env bun
/**
 * Resolves latest model IDs from Codex CLI cache, Google AI API, and Oracle CLI.
 * Writes sdlc-plugin/config/model-registry.md as the single source of truth.
 *
 * Usage:
 *   bun run scripts/resolve-models.ts            # resolve and write registry
 *   bun run scripts/resolve-models.ts --dry-run   # print without writing
 */

import { readFile, writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { join, dirname } from "path";
import { $ } from "bun";

// --- Types ---

export interface ModelEntry {
  id: string;
  notes: string;
}

export interface CodexCacheModel {
  slug: string;
  description: string;
  priority: number;
  visibility: "list" | "hide" | string;
}

export interface CodexResult {
  flagship: ModelEntry;
  fast?: ModelEntry;
  previous?: ModelEntry;
}

export interface GeminiResult {
  flagship: ModelEntry;
  fast?: ModelEntry;
}

export interface OracleResult {
  default: ModelEntry;
  alt?: ModelEntry;
}

interface GeminiApiModel {
  name: string;
  displayName?: string;
  description?: string;
}

// --- Codex resolution ---

export function resolveCodexModels(models: CodexCacheModel[]): CodexResult {
  const visible = models
    .filter((m) => m.visibility === "list")
    .sort((a, b) => a.priority - b.priority);

  if (visible.length === 0) {
    throw new Error("No visible Codex models found in cache");
  }

  const flagship = visible[0];
  const fast = visible.find((m) => m.slug.includes("mini"));
  const previous = visible.find(
    (m) => m.slug !== flagship.slug && !m.slug.includes("mini")
  );

  return {
    flagship: { id: flagship.slug, notes: flagship.description },
    ...(fast && { fast: { id: fast.slug, notes: fast.description } }),
    ...(previous && {
      previous: { id: previous.slug, notes: previous.description },
    }),
  };
}

// --- Gemini resolution ---

function parseGeminiVersion(name: string): number {
  // "models/gemini-3.1-pro-preview" → 3.1
  // "models/gemini-2.5-flash" → 2.5
  const match = name.match(/gemini-(\d+(?:\.\d+)?)/);
  return match ? parseFloat(match[1]) : 0;
}

export function resolveGeminiModels(models: GeminiApiModel[]): GeminiResult {
  // Exclude specialty variants (image, audio, tts, customtools, etc.)
  const isSpecialty = (name: string) =>
    /-(image|audio|tts|customtools|native)/.test(name);

  const geminiModels = models.filter(
    (m) => m.name.match(/gemini-\d/) && !isSpecialty(m.name)
  );

  // Strip "models/" prefix for IDs
  const stripPrefix = (name: string) => name.replace(/^models\//, "");

  // Find highest-version pro model
  const proModels = geminiModels
    .filter((m) => m.name.includes("-pro"))
    .sort((a, b) => parseGeminiVersion(b.name) - parseGeminiVersion(a.name));

  if (proModels.length === 0) {
    throw new Error("No Gemini pro models found in API response");
  }

  const flagship = proModels[0];

  // Find highest-version flash model (excluding -lite)
  const flashModels = geminiModels
    .filter((m) => m.name.includes("-flash") && !m.name.includes("-lite"))
    .sort((a, b) => parseGeminiVersion(b.name) - parseGeminiVersion(a.name));

  const fast = flashModels[0];

  return {
    flagship: {
      id: stripPrefix(flagship.name),
      notes: flagship.displayName || flagship.description || "Latest pro model",
    },
    ...(fast && {
      fast: {
        id: stripPrefix(fast.name),
        notes: fast.displayName || fast.description || "Latest flash model",
      },
    }),
  };
}

// --- Oracle resolution ---

export function resolveOracleModels(helpText: string): OracleResult {
  // Parse: "(gpt-5.4-pro default). Also gpt-5.4, gpt-5.1-pro"
  const defaultMatch = helpText.match(
    /\((\S+)\s+default\)/
  );
  if (!defaultMatch) {
    throw new Error("Could not parse Oracle default model from help output");
  }

  const defaultModel = defaultMatch[1];

  // Parse alternative models after "Also "
  const alsoMatch = helpText.match(/Also\s+([^)]+?)(?:\)|$)/m);
  let alt: ModelEntry | undefined;
  if (alsoMatch) {
    const altModels = alsoMatch[1]
      .split(",")
      .map((s) => s.trim().replace(/\.$/, ""))
      .filter(Boolean);
    if (altModels.length > 0) {
      alt = { id: altModels[0], notes: "Alternative reasoning model" };
    }
  }

  return {
    default: { id: defaultModel, notes: "Oracle CLI default" },
    ...(alt && { alt }),
  };
}

// --- Registry generation ---

export function generateRegistry(
  codex: Partial<CodexResult> & Pick<CodexResult, "flagship">,
  gemini: Partial<GeminiResult> & Pick<GeminiResult, "flagship">,
  oracle: Partial<OracleResult> & Pick<OracleResult, "default">
): string {
  const now = new Date().toISOString();

  const lines: string[] = [
    "<!-- AUTO-GENERATED by scripts/resolve-models.ts — DO NOT EDIT MANUALLY -->",
    `<!-- Last updated: ${now} -->`,
    "",
    "# Model Registry",
    "",
    "## Codex (OpenAI)",
    "",
    "| Role | Model ID | Notes |",
    "|------|----------|-------|",
    `| codex-flagship | ${codex.flagship.id} | ${codex.flagship.notes} |`,
  ];

  if (codex.fast) {
    lines.push(`| codex-fast | ${codex.fast.id} | ${codex.fast.notes} |`);
  }
  if (codex.previous) {
    lines.push(
      `| codex-previous | ${codex.previous.id} | ${codex.previous.notes} |`
    );
  }

  lines.push("", "## Gemini (Google)", "", "| Role | Model ID | Notes |", "|------|----------|-------|");
  lines.push(
    `| gemini-flagship | ${gemini.flagship.id} | ${gemini.flagship.notes} |`
  );
  if (gemini.fast) {
    lines.push(`| gemini-fast | ${gemini.fast.id} | ${gemini.fast.notes} |`);
  }

  lines.push("", "## Oracle", "", "| Role | Model ID | Notes |", "|------|----------|-------|");
  lines.push(
    `| oracle-default | ${oracle.default.id} | ${oracle.default.notes} |`
  );
  if (oracle.alt) {
    lines.push(`| oracle-alt | ${oracle.alt.id} | ${oracle.alt.notes} |`);
  }

  lines.push("");
  return lines.join("\n");
}

// --- Data source fetchers ---

async function fetchCodexCache(): Promise<CodexCacheModel[]> {
  const home = process.env.HOME || process.env.USERPROFILE || "";
  const cachePath = join(home, ".codex", "models_cache.json");

  try {
    const raw = await readFile(cachePath, "utf-8");
    const data = JSON.parse(raw);
    return data.models as CodexCacheModel[];
  } catch {
    console.warn("⚠ Could not read Codex models cache, trying OpenAI API...");
  }

  // Fallback: OpenAI API
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error("No Codex cache and no OPENAI_API_KEY set");

  const res = await fetch("https://api.openai.com/v1/models", {
    headers: { Authorization: `Bearer ${apiKey}` },
  });
  if (!res.ok) throw new Error(`OpenAI API error: ${res.status}`);

  const json = (await res.json()) as { data: Array<{ id: string }> };
  // Convert API models to cache format (estimate priority by version)
  return json.data
    .filter((m) => m.id.startsWith("gpt-5"))
    .map((m, i) => ({
      slug: m.id,
      description: m.id,
      priority: i,
      visibility: "list" as const,
    }))
    .sort((a, b) => {
      // Higher version = lower priority (better)
      const va = parseFloat(a.slug.match(/gpt-5\.?(\d+)?/)?.[1] || "0");
      const vb = parseFloat(b.slug.match(/gpt-5\.?(\d+)?/)?.[1] || "0");
      return vb - va;
    })
    .map((m, i) => ({ ...m, priority: i }));
}

async function fetchGeminiModels(): Promise<GeminiApiModel[]> {
  const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
  if (!apiKey) {
    console.warn("⚠ No GEMINI_API_KEY or GOOGLE_API_KEY set, using fallback Gemini models");
    return [
      { name: "models/gemini-2.5-pro", displayName: "Gemini 2.5 Pro", description: "Fallback pro" },
      { name: "models/gemini-2.5-flash", displayName: "Gemini 2.5 Flash", description: "Fallback flash" },
    ];
  }

  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`
  );
  if (!res.ok) {
    console.warn(`⚠ Google AI API error: ${res.status}, using fallback`);
    return [
      { name: "models/gemini-2.5-pro", displayName: "Gemini 2.5 Pro", description: "Fallback pro" },
      { name: "models/gemini-2.5-flash", displayName: "Gemini 2.5 Flash", description: "Fallback flash" },
    ];
  }

  const json = (await res.json()) as { models: GeminiApiModel[] };
  return json.models;
}

async function fetchOracleHelp(): Promise<string> {
  try {
    const result = await $`bunx @steipete/oracle --help 2>&1`.text();
    return result;
  } catch (e) {
    // bunx may exit non-zero but still print help
    if (e && typeof e === "object" && "stdout" in e) {
      return String((e as { stdout: unknown }).stdout);
    }
    throw new Error("Could not run oracle --help");
  }
}

// --- Main ---

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const scriptDir = dirname(new URL(import.meta.url).pathname);
  const pluginDir = join(scriptDir, "..");
  const registryPath = join(pluginDir, "config", "model-registry.md");

  console.log("Resolving models...\n");

  // Fetch all sources in parallel
  const [codexModels, geminiModels, oracleHelp] = await Promise.all([
    fetchCodexCache(),
    fetchGeminiModels(),
    fetchOracleHelp(),
  ]);

  // Resolve
  const codex = resolveCodexModels(codexModels);
  console.log(`  Codex flagship: ${codex.flagship.id}`);
  if (codex.fast) console.log(`  Codex fast:     ${codex.fast.id}`);
  if (codex.previous) console.log(`  Codex previous: ${codex.previous.id}`);

  const gemini = resolveGeminiModels(geminiModels);
  console.log(`  Gemini flagship: ${gemini.flagship.id}`);
  if (gemini.fast) console.log(`  Gemini fast:     ${gemini.fast.id}`);

  const oracle = resolveOracleModels(oracleHelp);
  console.log(`  Oracle default:  ${oracle.default.id}`);
  if (oracle.alt) console.log(`  Oracle alt:      ${oracle.alt.id}`);

  // Generate
  const registry = generateRegistry(codex, gemini, oracle);

  if (dryRun) {
    console.log("\n--- DRY RUN (would write to config/model-registry.md) ---\n");
    console.log(registry);
    return;
  }

  // Ensure config directory exists
  const configDir = join(pluginDir, "config");
  if (!existsSync(configDir)) {
    await mkdir(configDir, { recursive: true });
  }

  // Check for changes
  let changed = true;
  if (existsSync(registryPath)) {
    const existing = await readFile(registryPath, "utf-8");
    // Compare ignoring timestamp line
    const stripTimestamp = (s: string) =>
      s.replace(/<!-- Last updated: .* -->/, "");
    changed = stripTimestamp(existing) !== stripTimestamp(registry);
  }

  await writeFile(registryPath, registry);

  if (changed) {
    console.log("\n✅ Registry updated at config/model-registry.md");
  } else {
    console.log("\n✅ Registry is up to date (no model changes)");
  }
}

// Only run main when executed directly (not imported for tests)
if (import.meta.main) {
  main().catch((err) => {
    console.error("❌ Failed to resolve models:", err.message);
    process.exit(1);
  });
}
